version: "3.3"

services:
  check-files:
    build: "."
    image: check-files
    container_name: check-files-container
    volumes:
      - ./notebooks:/root/notebooks
    expose:
      - 8888
    ports:
      - "8887:8888"

    restart: always
